# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_hand_controller
    - right_hand_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - ur5_left_shoulder_pan_joint
      - ur5_left_shoulder_lift_joint
      - ur5_left_elbow_joint
      - ur5_left_wrist_1_joint
      - ur5_left_wrist_2_joint
      - ur5_left_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - ur5_right_shoulder_pan_joint
      - ur5_right_shoulder_lift_joint
      - ur5_right_elbow_joint
      - ur5_right_wrist_1_joint
      - ur5_right_wrist_2_joint
      - ur5_right_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  left_hand_controller:
    type: GripperCommand
    joints:
      - left_gripper_robotiq_85_left_knuckle_joint
    action_ns: gripper_cmd
    default: true
  right_hand_controller:
    type: GripperCommand
    joints:
      - right_gripper_robotiq_85_left_knuckle_joint
    action_ns: gripper_cmd
    default: true